### ISSUE TITLE
Polishing Steps

### ISSUE THREAD

**Issue by AndrewJSchoen** [Wisc-HCI/authr#1]
- [x] Update Authr README files
  - [x] Rework and finalize Meta README
  - [x] Include updated install in Meta README
  - [x] Document Package dependencies
- [x] Review LICENSE information
- [x] Fix static build of Authr

**Comment by curthenrichs** [comment]
- [x] Rework Authr package README

**Comment by curthenrichs** [comment]
We should update the Authr PDDL License to separate out our software and the included tools.
